# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'candeploy'
    subscriptionId: 'c7d4ef2e-d5ee-4cd2-b88c-c435f6281b52'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'fuck'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.SourcesDirectory)/blob/master/quickstarts/microsoft.compute/vm-simple-windows/azuredeploy.json'
    csmParametersFile: '$(Build.SourcesDirectory)/blob/master/quickstarts/microsoft.compute/vm-simple-windows/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'